name: RM
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - _pytorch_select=0.2=gpu_0
  - asn1crypto=1.3.0=py37_0
  - blas=2.16=openblas
  - boto=2.49.0=py_0
  - boto3=1.17.53=pyhd8ed1ab_0
  - botocore=1.20.112=pyhd8ed1ab_0
  - brotlipy=0.7.0=py37h8f50634_1000
  - bz2file=0.98=py_0
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2021.1.19=h06a4308_0
  - certifi=2020.12.5=py37h89c1867_1
  - cffi=1.14.0=py37hd463f26_0
  - chardet=3.0.4=py37hc8dfbb8_1006
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=2.8=py37hb09aad4_2
  - cudatoolkit=10.0.130=hf841e97_6
  - cudnn=7.6.5.32=ha8d7eb6_1
  - decorator=4.4.2=py_0
  - docutils=0.15.2=py37_0
  - freetype=2.10.1=he06d7ca_0
  - gensim=3.8.1=py37he1b5a44_1
  - google-api-core=1.17.0=py37hc8dfbb8_0
  - google-auth=1.14.0=pyh9f0ad1d_0
  - google-cloud-core=1.3.0=py_0
  - google-cloud-storage=1.27.0=pyh9f0ad1d_0
  - google-resumable-media=0.5.0=py_1
  - intel-openmp=2020.2=254
  - jenkspy=0.1.4=py37h516909a_1000
  - jmespath=0.9.5=py_0
  - jpeg=9c=h14c3975_1001
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgfortran-ng=7.3.0=hdf63c60_5
  - liblapack=3.8.0=16_openblas
  - liblapacke=3.8.0=16_openblas
  - libopenblas=0.3.9=h5ec1e0e_0
  - libpng=1.6.37=hed695b0_1
  - libprotobuf=3.11.4=h8b12597_0
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.1.0=hc7e4089_6
  - libwebp-base=1.1.0=h516909a_3
  - llvm-openmp=11.0.1=h4bd325d_0
  - lz4-c=1.9.2=he1b5a44_0
  - mkl=2020.4=h726a3e6_304
  - mkl-service=2.3.0=py37h8f50634_2
  - mkl_fft=1.2.0=py37h161383b_1
  - mkl_random=1.2.0=py37h9fdb41a_1
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.4=py_1
  - ninja=1.10.0=hc9558a2_0
  - nltk=3.4.4=py_0
  - numpy=1.19.5=py37haa41c4c_1
  - olefile=0.46=py_0
  - openssl=1.1.1j=h27cfd23_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_0
  - pyopenssl=19.1.0=py_1
  - pysocks=1.7.1=py37hc8dfbb8_1
  - python=3.7.6=h8356626_5_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch-pretrained-bert=0.6.2=py37_0
  - pytz=2019.3=py_0
  - readline=8.0=hf8c457e_0
  - regex=2021.8.3=py37h5e8e339_0
  - rsa=4.0=py_0
  - s3transfer=0.3.3=py37hc8dfbb8_1
  - scipy=1.5.2=py37hb14ef9d_0
  - setuptools=46.1.3=py37hc8dfbb8_0
  - six=1.14.0=py_1
  - smart_open=1.11.1=pyh9f0ad1d_0
  - sqlite=3.30.1=hcee41ef_0
  - tensorboardx=2.0=py_0
  - tk=8.6.10=hed695b0_0
  - tqdm=4.62.3=pyhd8ed1ab_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.25.11=py_0
  - wheel=0.34.2=py_1
  - xz=5.2.5=h516909a_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h6597ccf_3
  - pip:
    - absl-py==0.12.0
    - altair==4.1.0
    - appdirs==1.4.4
    - argcomplete==1.12.3
    - argon2-cffi==21.1.0
    - astor==0.8.1
    - attrs==21.2.0
    - backcall==0.2.0
    - backports-csv==1.0.7
    - backports-zoneinfo==0.2.1
    - base58==2.1.1
    - beautifulsoup4==4.10.0
    - black==20.8b1
    - bleach==4.1.0
    - blinker==1.4
    - blis==0.7.5
    - cached-property==1.5.2
    - cachetools==4.2.4
    - catalogue==1.0.0
    - cheroot==8.5.2
    - cherrypy==18.6.1
    - click==7.1.2
    - cloudpickle==2.0.0
    - codecov==2.1.12
    - conllu==4.4
    - coverage==6.1.1
    - cycler==0.11.0
    - cymem==2.0.6
    - debugpy==1.5.1
    - defusedxml==0.7.1
    - dill==0.3.4
    - docker-pycreds==0.4.0
    - elasticsearch==7.15.1
    - en-core-web-lg==2.3.1
    - en-core-web-sm==2.3.1
    - entrypoints==0.3
    - execnet==1.9.0
    - feedparser==6.0.8
    - filelock==3.0.12
    - flake8==4.0.1
    - flaky==3.7.0
    - flask==2.0.2
    - ftfy==6.0.3
    - future==0.18.2
    - git-python==1.0.3
    - gitdb==4.0.9
    - gitpython==3.1.24
    - googleapis-common-protos==1.53.0
    - gunicorn==20.1.0
    - h5py==3.5.0
    - huggingface-hub==0.1.0
    - idna==2.8
    - importlib-metadata==4.2.0
    - importlib-resources==5.4.0
    - inflect==5.3.0
    - iniconfig==1.1.1
    - ipykernel==6.9.1
    - ipython==7.29.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - itsdangerous==2.0.1
    - jaraco-classes==3.2.1
    - jaraco-collections==3.4.0
    - jaraco-functools==3.4.0
    - jaraco-text==3.6.0
    - jedi==0.18.0
    - jeepney==0.7.1
    - jinja2==3.0.2
    - joblib==1.1.0
    - jpype1==1.3.0
    - jsonnet==0.17.0
    - jsonpickle==2.0.0
    - jsonschema==4.2.1
    - jupyter-client==7.1.2
    - jupyter-core==4.9.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - keyring==23.2.1
    - kiwisolver==1.3.2
    - livereload==2.6.3
    - lmdb==1.2.1
    - lunr==0.5.8
    - lxml==4.6.4
    - markdown==3.3.4
    - markdown-include==0.6.0
    - markupsafe==2.0.1
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.3
    - mccabe==0.6.1
    - mistune==0.8.4
    - mkdocs==1.1.2
    - mkdocs-material==6.2.8
    - mkdocs-material-extensions==1.0.3
    - more-itertools==8.10.0
    - murmurhash==1.0.6
    - mypy==0.800
    - mypy-extensions==0.4.3
    - mysqlclient==2.0.3
    - nbclient==0.5.4
    - nbconvert==6.2.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.5
    - nr-collections==0.0.1
    - nr-databind-core==0.0.16
    - nr-databind-json==0.0.13
    - nr-interface==0.0.3
    - nr-metaclass==0.0.6
    - nr-parsing-date==0.6.1
    - nr-pylang-utils==0.0.4
    - nr-stream==0.0.5
    - nr-utils-re==0.1.1
    - overrides==3.1.0
    - packaging==21.2
    - pandas==1.3.4
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pathspec==0.9.0
    - pathtools==0.1.2
    - pattern==3.6
    - pdfminer-six==20211012
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.4.0
    - pkginfo==1.7.1
    - plac==1.1.3
    - pluggy==1.0.0
    - portalocker==2.3.2
    - portend==3.0.0
    - preshed==3.0.6
    - prometheus-client==0.12.0
    - promise==2.3
    - prompt-toolkit==3.0.22
    - protobuf==3.19.1
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - py==1.11.0
    - py-cpuinfo==8.0.0
    - py-rouge==1.1
    - pyarrow==6.0.0
    - pycodestyle==2.8.0
    - pydeck==0.7.1
    - pydoc-markdown==3.0.2
    - pyflakes==2.4.0
    - pygments==2.10.0
    - pymdown-extensions==9.0
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - pytest==6.2.5
    - pytest-benchmark==3.4.1
    - pytest-cov==3.0.0
    - pytest-forked==1.3.0
    - pytest-xdist==2.4.0
    - python-docx==0.8.11
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==5.4.1
    - pyzmq==22.3.0
    - readme-renderer==30.0
    - requests==2.22.0
    - requests-toolbelt==0.9.1
    - responses==0.15.0
    - rfc3986==1.5.0
    - rouge==1.0.1
    - rouge-metric==1.0.1
    - rouge-score==0.0.4
    - ruamel-yaml==0.17.17
    - ruamel-yaml-clib==0.2.6
    - sacrebleu==2.0.0
    - sacremoses==0.0.46
    - scikit-learn==1.0.1
    - secretstorage==3.3.1
    - send2trash==1.8.0
    - sentence-transformers==2.1.0
    - sentencepiece==0.1.96
    - sentry-sdk==1.5.6
    - sgmllib3k==1.0.0
    - shortuuid==1.0.8
    - smmap==5.0.0
    - soupsieve==2.3
    - spacy==2.3.7
    - spyder-kernels==2.2.1
    - srsly==1.0.5
    - streamlit==1.1.0
    - tabulate==0.8.9
    - tempora==4.1.2
    - tensorflow-datasets==4.4.0
    - tensorflow-metadata==1.4.0
    - termcolor==1.1.0
    - terminado==0.12.1
    - testpath==0.5.0
    - thinc==7.4.5
    - threadpoolctl==3.0.0
    - tokenizers==0.10.3
    - toml==0.10.2
    - tomli==1.2.2
    - toolz==0.11.1
    - torch==1.7.1
    - torchvision==0.8.2
    - tornado==6.1
    - traitlets==5.1.1
    - transformers==4.3.3
    - twine==3.5.0
    - typed-ast==1.4.3
    - tzdata==2021.5
    - tzlocal==4.1
    - validators==0.18.2
    - wandb==0.12.10
    - wasabi==0.8.2
    - watchdog==0.10.4
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.0.2
    - widgetsnbextension==3.5.2
    - wmd==1.3.2
    - word2number==1.1
    - wurlitzer==3.0.2
    - yaspin==2.1.0
    - zc-lockfile==2.0
    - zipp==3.6.0
prefix: /home/becky/.conda/envs/RM
